# Generated by Django 5.1 on 2024-08-16 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='nombre',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='apellido',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='telefono',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='empresa',
            new_name='company',
        ),
    ]
