# Generated by Django 5.1 on 2024-09-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_person_options_rename_nombre_client_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cuit',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
