# Generated by Django 5.1 on 2026-01-23 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_person_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentaccount',
            name='client',
        ),
        migrations.RemoveField(
            model_name='currentaccount',
            name='supplier',
        ),
        migrations.AddField(
            model_name='currentaccount',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.person'),
        ),
        migrations.AlterField(
            model_name='currentaccount',
            name='resumen',
            field=models.TextField(blank=True),
        ),
    ]
