# Generated by Django 5.1 on 2026-01-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_currentaccount_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa/Verdulería'),
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='administrator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Administrativo'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='salesperson',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company',
            field=models.CharField(max_length=50, verbose_name='Empresa'),
        ),
    ]
