# Generated by Django 5.1 on 2026-02-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_client_business_name_person_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentaccount',
            options={'verbose_name': 'Cuenta Corriente', 'verbose_name_plural': 'Cuentas Corrientes'},
        ),
        migrations.RemoveField(
            model_name='currentaccount',
            name='resumen',
        ),
        migrations.AddField(
            model_name='currentaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='currentaccount',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='currentaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
