# Generated by Django 5.1 on 2026-02-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_currentaccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentaccount',
            name='account_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Número de Cuenta'),
        ),
    ]
