# Generated by Django 5.1 on 2024-08-16 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('initial_amounts', models.JSONField(default=dict)),
                ('final_amounts', models.JSONField(default=dict)),
                ('differences', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='O', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.currentaccount')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.cashregister')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finances.ticket')),
                ('payment_method', models.CharField(blank=True, choices=[('CA', 'Cash'), ('TR', 'Transfer'), ('CH', 'Check'), ('AC', 'Account')], max_length=2, null=True)),
                ('payment_type', models.CharField(choices=[('I', 'Income'), ('E', 'Expense')], default='S', max_length=2)),
            ],
            bases=('finances.ticket',),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finances.ticket')),
                ('temporal_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('finances.ticket',),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finances.ticket')),
                ('temporal_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('CA', 'Canceled'), ('CC', 'CurrentAccount'), ('PA', 'Paid'), ('CO', 'Completed')], default='PE', max_length=2)),
                ('payment_method', models.CharField(blank=True, choices=[('CA', 'Cash'), ('TR', 'Transfer'), ('CH', 'Check'), ('AC', 'Account')], max_length=2, null=True)),
            ],
            bases=('finances.ticket',),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finances.purchase')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finances.sale')),
            ],
        ),
    ]
