# Generated by Django 5.1 on 2024-08-17 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_ticket_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='register',
        ),
    ]
