# Generated by Django 5.1.4 on 2025-06-03 21:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_remove_ticket_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
