# Generated by Django 5.1.4 on 2025-06-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_alter_item_subtotal_alter_ticket_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_name_cache',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
