# Generated by Django 5.1.4 on 2025-07-08 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_remove_ticket_date_ticket_date_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'Sale'), ('P', 'Purchase'), ('E', 'Expense'), ('I', 'Income')], max_length=1)),
                ('year', models.PositiveIntegerField()),
                ('number', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='ticket_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.numticket'),
        ),
    ]
