# Generated by Django 5.1 on 2026-01-23 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_client_business_name_person_city_and_more'),
        ('finances', '0007_numticket_sale_ticket_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.person', verbose_name='Cliente/Proveedor'),
        ),
    ]
