# Generated by Django 5.1 on 2026-01-23 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_ticket_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numticket',
            name='type',
            field=models.CharField(choices=[('S', 'Sale'), ('P', 'Purchase'), ('E', 'Expense'), ('I', 'Income'), ('PA', 'Payment'), ('CN', 'CreditNote')], max_length=2),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finances.ticket')),
                ('note_type', models.CharField(choices=[('S', 'Sale'), ('P', 'Purchase')], default='S', max_length=2, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('CA', 'Canceled'), ('CC', 'CurrentAccount'), ('PA', 'Paid'), ('CO', 'Completed')], default='PE', max_length=2)),
                ('ticket_code', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.numticket')),
            ],
            bases=('finances.ticket',),
        ),
    ]
