# Generated by Django 5.1 on 2026-01-23 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_alter_numticket_type_creditnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='ticket_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.numticket'),
        ),
    ]
