# Generated by Django 5.1 on 2026-02-12 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_purchase_ticket_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='delivery_status',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('CO', 'Completado'), ('IN', 'Incompleto'), ('CA', 'Cancelado')], default='PE', max_length=2, verbose_name='Estado de Entrega'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('PP', 'Pago Parcial'), ('PA', 'Pagado')], default='PE', max_length=2, verbose_name='Estado de Pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CA', 'Efectivo'), ('TR', 'Transferencia'), ('CH', 'Cheque')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CA', 'Efectivo'), ('TR', 'Transferencia'), ('CH', 'Cheque')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(blank=True, choices=[('PE', 'Pending'), ('CA', 'Canceled'), ('CC', 'CurrentAccount'), ('PA', 'Paid'), ('CO', 'Completed')], default='PE', max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('payment_method', models.CharField(choices=[('CA', 'Efectivo'), ('TR', 'Transferencia'), ('CH', 'Cheque')], max_length=2, verbose_name='Método de Pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('is_reverted', models.BooleanField(default=False, verbose_name='Revertido')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='finances.sale')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Detalle de Pago',
                'verbose_name_plural': 'Detalles de Pago',
                'ordering': ['created_at'],
            },
        ),
    ]
