# Generated by Django 5.1 on 2026-02-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_sale_delivery_status_sale_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='delivery_status',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('CO', 'Completado'), ('IN', 'Incompleto')], default='PE', max_length=2, verbose_name='Estado de Entrega'),
        ),
    ]
