# Generated by Django 5.1.4 on 2026-05-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_cheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='delivery_status',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('CO', 'Completado'), ('IN', 'Incompleto')], default='PE', max_length=2, verbose_name='Estado de Entrega'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_status',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('PP', 'Pago Parcial'), ('PA', 'Pagado')], default='PE', max_length=2, verbose_name='Estado de Pago'),
        ),
    ]
