# Generated by Django 5.1.4 on 2026-05-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0014_purchase_delivery_status_purchase_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(blank=True, choices=[('PE', 'Pending'), ('CA', 'Canceled'), ('CC', 'CurrentAccount'), ('PA', 'Paid'), ('CO', 'Completed')], max_length=2, null=True),
        ),
    ]
