# Generated by Django 5.1.4 on 2026-05-16 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0015_purchase_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='delivery_status',
        ),
    ]
