# Generated by Django 5.1 on 2026-01-29 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_client_business_name_person_city_and_more'),
        ('finances', '0010_purchase_ticket_code'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, help_text='Ej: cajón, kg, unidad', max_length=50, null=True, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio referencia'),
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(verbose_name='Fecha de ingreso')),
                ('initial_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad inicial')),
                ('current_stock', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock actual')),
                ('losses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pérdidas acumuladas')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Precio acordado con proveedor', max_digits=10, verbose_name='Precio base')),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de flete')),
                ('entry_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de entradas')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, help_text='Costo final por unidad (incluye todos los gastos)', max_digits=10, verbose_name='Precio costo unitario')),
                ('suggested_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio sugerido de venta')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product', verbose_name='Producto')),
                ('related_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_batches', to='finances.ticket', verbose_name='Compra relacionada')),
                ('supplier', models.ForeignKey(blank=True, limit_choices_to={'supplier__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.person', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Lote de producto',
                'verbose_name_plural': 'Lotes de productos',
                'ordering': ['-entry_date', 'product__name'],
            },
        ),
    ]
